// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// ---------------------------------------------------------------------------
// هذا الملف تم توليده تلقائياً بواسطة أداة FlutterFire CLI.
// ---------------------------------------------------------------------------
// الغرض منه:
// يحتوي على مفاتيح وإعدادات الاتصال بمشروع Firebase الخاص بالتطبيق.
// بدلاً من وضع ملفات json أو plist يدوياً لكل منصة، هذا الملف يجمع كل
// الإعدادات في مكان واحد بلغة Dart.
//
// وظيفته:
// عند تشغيل التطبيق (في ملف main.dart)، نستخدم هذا الكلاس لتحديد الإعدادات
// المناسبة للمنصة التي يعمل عليها التطبيق حالياً (Android, iOS, Web, Windows).
// ---------------------------------------------------------------------------

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // ---------------------------------------------------------------------------
  // دالة ذكية تحدد المنصة الحالية وتعيد الإعدادات الموافقة لها
  // ---------------------------------------------------------------------------
  static FirebaseOptions get currentPlatform {
    // 1. هل التطبيق يعمل على المتصفح (Web)؟
    if (kIsWeb) {
      return web;
    }
    // 2. إذا لم يكن ويب، نتحقق من نوع نظام التشغيل
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // Linux غير مدعوم حالياً في هذه الإعدادات
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ---------------------------------------------------------------------------
  // إعدادات Firebase الخاصة بالويب (Web)
  // ---------------------------------------------------------------------------
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb1kNhVWqN20vb9_sl_xSWRvxGImqfRpk',
    appId: '1:162787630610:web:29cf40b56b553a6d7e42cb',
    messagingSenderId: '162787630610',
    projectId: 'goal-tracking-ba066',
    authDomain: 'goal-tracking-ba066.firebaseapp.com',
    storageBucket: 'goal-tracking-ba066.firebasestorage.app',
    measurementId: 'G-BQZ1MZ86YB',
  );

  // ---------------------------------------------------------------------------
  // إعدادات Firebase الخاصة بالأندرويد (Android)
  // ---------------------------------------------------------------------------
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwtI9MvyA2zweBQeUp_TqPojbEGyVm-e8',
    appId: '1:162787630610:android:c931a4e5f6bb2eb57e42cb',
    messagingSenderId: '162787630610',
    projectId: 'goal-tracking-ba066',
    storageBucket: 'goal-tracking-ba066.firebasestorage.app',
  );

  // ---------------------------------------------------------------------------
  // إعدادات Firebase الخاصة بالآيفون (iOS)
  // ---------------------------------------------------------------------------
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgyP79Q4Vj350k8OqLHCfjYa1v39LqNGA',
    appId: '1:162787630610:ios:5cc773bf9208d1697e42cb',
    messagingSenderId: '162787630610',
    projectId: 'goal-tracking-ba066',
    storageBucket: 'goal-tracking-ba066.firebasestorage.app',
    iosBundleId: 'com.example.goalManagerApp',
  );

  // ---------------------------------------------------------------------------
  // إعدادات Firebase الخاصة بالماك (macOS)
  // ---------------------------------------------------------------------------
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgyP79Q4Vj350k8OqLHCfjYa1v39LqNGA',
    appId: '1:162787630610:ios:5cc773bf9208d1697e42cb',
    messagingSenderId: '162787630610',
    projectId: 'goal-tracking-ba066',
    storageBucket: 'goal-tracking-ba066.firebasestorage.app',
    iosBundleId: 'com.example.goalManagerApp',
  );

  // ---------------------------------------------------------------------------
  // إعدادات Firebase الخاصة بالويندوز (Windows)
  // ---------------------------------------------------------------------------
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb1kNhVWqN20vb9_sl_xSWRvxGImqfRpk',
    appId: '1:162787630610:web:afd15106e94984337e42cb',
    messagingSenderId: '162787630610',
    projectId: 'goal-tracking-ba066',
    authDomain: 'goal-tracking-ba066.firebaseapp.com',
    storageBucket: 'goal-tracking-ba066.firebasestorage.app',
    measurementId: 'G-VZLYVH1HDV',
  );
}
