// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb1kNhVWqN20vb9_sl_xSWRvxGImqfRpk',
    appId: '1:162787630610:web:29cf40b56b553a6d7e42cb',
    messagingSenderId: '162787630610',
    projectId: 'goal-tracking-ba066',
    authDomain: 'goal-tracking-ba066.firebaseapp.com',
    storageBucket: 'goal-tracking-ba066.firebasestorage.app',
    measurementId: 'G-BQZ1MZ86YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwtI9MvyA2zweBQeUp_TqPojbEGyVm-e8',
    appId: '1:162787630610:android:c931a4e5f6bb2eb57e42cb',
    messagingSenderId: '162787630610',
    projectId: 'goal-tracking-ba066',
    storageBucket: 'goal-tracking-ba066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgyP79Q4Vj350k8OqLHCfjYa1v39LqNGA',
    appId: '1:162787630610:ios:5cc773bf9208d1697e42cb',
    messagingSenderId: '162787630610',
    projectId: 'goal-tracking-ba066',
    storageBucket: 'goal-tracking-ba066.firebasestorage.app',
    iosBundleId: 'com.example.goalManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgyP79Q4Vj350k8OqLHCfjYa1v39LqNGA',
    appId: '1:162787630610:ios:5cc773bf9208d1697e42cb',
    messagingSenderId: '162787630610',
    projectId: 'goal-tracking-ba066',
    storageBucket: 'goal-tracking-ba066.firebasestorage.app',
    iosBundleId: 'com.example.goalManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb1kNhVWqN20vb9_sl_xSWRvxGImqfRpk',
    appId: '1:162787630610:web:afd15106e94984337e42cb',
    messagingSenderId: '162787630610',
    projectId: 'goal-tracking-ba066',
    authDomain: 'goal-tracking-ba066.firebaseapp.com',
    storageBucket: 'goal-tracking-ba066.firebasestorage.app',
    measurementId: 'G-VZLYVH1HDV',
  );
}
